### ISSUE TITLE
Duplicate directory

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-packages3D-source#245]
There exists both `Sensor.3dshapes` and `Sensors.3dshapes` directories. **kicad-packages3D** only contains `Sensor.3dshapes`.

**Comment by DanSGiesbrecht** [comment]
Would 6.0.0 be a suitable milestone for this?

**Comment by poeschlr** [comment]
You could fix this right away. The sensors.pretty directory here is a remand from v4. (That was forgotten in the source repo)
